import afterHoursCover from "@/assets/after-hours.jpg";
import nightCover from "@/assets/night.jpg";
import sunflowerCover from "@/assets/sunflower.jpg";
import dawnCover from "@/assets/dawn-fm.jpg";
import tranquilityCover from "@/assets/tranquility.jpg";
import oceanCover from "@/assets/ocean.jpg";

export interface ArtistVideo {
  id: string;
  title: string;
  channel: string;
  duration: string;
  thumbnail: string;
  views?: string;
  date?: string;
}

export interface ArtistProfile {
  name: string;
  handle: string;
  cover: string;
  fallbackCover: string;
  banner?: string;
  subscribers: string;
  videosCount: string;
  totalViews: string;
  bio: string;
  verified: boolean;
  featuredVideos: ArtistVideo[];
}

export const DEFAULT_FEATURED_VIDEO: ArtistVideo = {
  id: "V9PVRfjEBTI",
  title: "Billie Eilish - BIRDS OF A FEATHER (Official Music Video)",
  channel: "Billie Eilish",
  duration: "3:13",
  thumbnail: "https://i.ytimg.com/vi/V9PVRfjEBTI/hqdefault.jpg",
  views: "120M views",
  date: "HIT ME HARD AND SOFT",
};

export const ARTIST_PROFILES: Record<string, ArtistProfile> = {
  "Billie Eilish": {
    name: "Billie Eilish",
    handle: "@BillieEilish",
    cover:
      "https://yt3.googleusercontent.com/dirvtoDAmx-u0UR76-pxfhYL6Wxj2vfL2geUcxDwk62tTWWhGG6QDGc63RG3NdOz38-yBwRHDQ=s900-c-k-c0x00ffffff-no-rj",
    fallbackCover: sunflowerCover,
    banner:
      "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=1200&auto=format&fit=crop&q=80",
    subscribers: "50.9M subscribers",
    videosCount: "135 videos",
    totalViews: "34.1B views",
    bio: "Official YouTube Channel of Billie Eilish. Stream the new album 'HIT ME HARD AND SOFT' out now worldwide.",
    verified: true,
    featuredVideos: [
      {
        id: "V9PVRfjEBTI",
        title: "BIRDS OF A FEATHER (Official Music Video)",
        channel: "Billie Eilish",
        duration: "3:13",
        thumbnail: "https://i.ytimg.com/vi/V9PVRfjEBTI/hqdefault.jpg",
        views: "120M views",
        date: "HIT ME HARD AND SOFT",
      },
      {
        id: "MB3VkzPdgLA",
        title: "LUNCH (Official Music Video)",
        channel: "Billie Eilish",
        duration: "3:00",
        thumbnail: "https://i.ytimg.com/vi/MB3VkzPdgLA/hqdefault.jpg",
        views: "85M views",
        date: "HIT ME HARD AND SOFT",
      },
      {
        id: "DyDfgMOUjCI",
        title: "bad guy (Official Music Video)",
        channel: "Billie Eilish",
        duration: "3:25",
        thumbnail: "https://i.ytimg.com/vi/DyDfgMOUjCI/hqdefault.jpg",
        views: "1.3B views",
        date: "WHEN WE ALL FALL ASLEEP",
      },
      {
        id: "V1Pl8CzNzCw",
        title: "lovely (with Khalid)",
        channel: "Billie Eilish",
        duration: "3:20",
        thumbnail: "https://i.ytimg.com/vi/V1Pl8CzNzCw/hqdefault.jpg",
        views: "2.1B views",
        date: "13 Reasons Why",
      },
      {
        id: "pbMwTqkKSps",
        title: "when the party's over (Official Music Video)",
        channel: "Billie Eilish",
        duration: "3:14",
        thumbnail: "https://i.ytimg.com/vi/pbMwTqkKSps/hqdefault.jpg",
        views: "920M views",
        date: "Classic Single",
      },
      {
        id: "egUW7yp44iE",
        title: "Happier Than Ever (Official Music Video)",
        channel: "Billie Eilish",
        duration: "5:15",
        thumbnail: "https://i.ytimg.com/vi/egUW7yp44iE/hqdefault.jpg",
        views: "340M views",
        date: "Happier Than Ever",
      },
      {
        id: "viimfQi_pUw",
        title: "ocean eyes (Official Music Video)",
        channel: "Billie Eilish",
        duration: "3:16",
        thumbnail: "https://i.ytimg.com/vi/viimfQi_pUw/hqdefault.jpg",
        views: "610M views",
        date: "dont smile at me",
      },
      {
        id: "HUHC9tYz8ik",
        title: "bury a friend (Official Music Video)",
        channel: "Billie Eilish",
        duration: "3:32",
        thumbnail: "https://i.ytimg.com/vi/HUHC9tYz8ik/hqdefault.jpg",
        views: "480M views",
        date: "WHEN WE ALL FALL ASLEEP",
      },
      {
        id: "egk4gNfWp80",
        title: "everything i wanted (Official Video)",
        channel: "Billie Eilish",
        duration: "4:47",
        thumbnail: "https://i.ytimg.com/vi/egk4gNfWp80/hqdefault.jpg",
        views: "370M views",
        date: "Grammy Winner",
      },
      {
        id: "BY_X02fe79U",
        title: "CHIHIRO (Official Music Video)",
        channel: "Billie Eilish",
        duration: "5:03",
        thumbnail: "https://i.ytimg.com/vi/BY_X02fe79U/hqdefault.jpg",
        views: "65M views",
        date: "HIT ME HARD AND SOFT",
      },
    ],
  },

  "The Weeknd": {
    name: "The Weeknd",
    handle: "@TheWeeknd",
    cover:
      "https://yt3.googleusercontent.com/WHvw1ak1FcJaHeEiTmG2iN0dqEjjPxAtT_tA8ruJ3MlNr9I-RHsAur1iAenYeQN_d6LNPH2Z8Ic=s900-c-k-c0x00ffffff-no-rj",
    fallbackCover: afterHoursCover,
    banner:
      "https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=1200&auto=format&fit=crop&q=80",
    subscribers: "35.8M subscribers",
    videosCount: "192 videos",
    totalViews: "25.2B views",
    bio: "Official YouTube Channel of The Weeknd. Stream new single 'Dancing in the Flames' and the latest global hits.",
    verified: true,
    featuredVideos: [
      {
        id: "m7FkZ_9pL1A",
        title: "Dancing in the Flames (Official Music Video)",
        channel: "The Weeknd",
        duration: "3:40",
        thumbnail: "https://i.ytimg.com/vi/m7FkZ_9pL1A/hqdefault.jpg",
        views: "45M views",
        date: "Hurry Up Tomorrow",
      },
      {
        id: "4NRXx6U8ABQ",
        title: "Blinding Lights (Official Music Video)",
        channel: "The Weeknd",
        duration: "4:20",
        thumbnail: "https://i.ytimg.com/vi/4NRXx6U8ABQ/hqdefault.jpg",
        views: "890M views",
        date: "After Hours",
      },
      {
        id: "XXYlFuWEuKI",
        title: "Save Your Tears (Official Music Video)",
        channel: "The Weeknd",
        duration: "4:08",
        thumbnail: "https://i.ytimg.com/vi/XXYlFuWEuKI/hqdefault.jpg",
        views: "1.2B views",
        date: "After Hours",
      },
      {
        id: "34Na4j8AVgA",
        title: "Starboy ft. Daft Punk (Official Music Video)",
        channel: "The Weeknd",
        duration: "3:50",
        thumbnail: "https://i.ytimg.com/vi/34Na4j8AVgA/hqdefault.jpg",
        views: "2.3B views",
        date: "Starboy",
      },
      {
        id: "uPD0QOGChkM",
        title: "Die For You (Official Music Video)",
        channel: "The Weeknd",
        duration: "4:20",
        thumbnail: "https://i.ytimg.com/vi/uPD0QOGChkM/hqdefault.jpg",
        views: "320M views",
        date: "Starboy",
      },
      {
        id: "KEI4qS4P-3Y",
        title: "Can't Feel My Face (Official Video)",
        channel: "The Weeknd",
        duration: "3:39",
        thumbnail: "https://i.ytimg.com/vi/KEI4qS4P-3Y/hqdefault.jpg",
        views: "1.4B views",
        date: "Beauty Behind the Madness",
      },
      {
        id: "yzTuBuRdAyA",
        title: "The Hills (Official Music Video)",
        channel: "The Weeknd",
        duration: "3:55",
        thumbnail: "https://i.ytimg.com/vi/yzTuBuRdAyA/hqdefault.jpg",
        views: "2.0B views",
        date: "Classic Hit",
      },
    ],
  },

  "Kendrick Lamar": {
    name: "Kendrick Lamar",
    handle: "@KendrickLamarMusic",
    cover:
      "https://yt3.googleusercontent.com/ytc/AIdro_mJoVPMBjJ0WNhRgNoQeztGbf1fbHjWlrP72VWlTr0rBg=s900-c-k-c0x00ffffff-no-rj",
    fallbackCover: nightCover,
    banner:
      "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=1200&auto=format&fit=crop&q=80",
    subscribers: "15.4M subscribers",
    videosCount: "86 videos",
    totalViews: "11.5B views",
    bio: "Pulitzer Prize-winning artist. Official YouTube Channel of Kendrick Lamar / pgLang.",
    verified: true,
    featuredVideos: [
      {
        id: "H58vbez_m4E",
        title: "Not Like Us (Official Music Video)",
        channel: "Kendrick Lamar",
        duration: "4:34",
        thumbnail: "https://i.ytimg.com/vi/H58vbez_m4E/hqdefault.jpg",
        views: "180M views",
        date: "2024 Global Hit",
      },
      {
        id: "tvTRZJ-4EyI",
        title: "HUMBLE. (Official Music Video)",
        channel: "Kendrick Lamar",
        duration: "3:04",
        thumbnail: "https://i.ytimg.com/vi/tvTRZJ-4EyI/hqdefault.jpg",
        views: "980M views",
        date: "DAMN.",
      },
      {
        id: "NLZRYQMLDW4",
        title: "DNA. (Official Music Video)",
        channel: "Kendrick Lamar",
        duration: "4:46",
        thumbnail: "https://i.ytimg.com/vi/NLZRYQMLDW4/hqdefault.jpg",
        views: "340M views",
        date: "DAMN.",
      },
      {
        id: "GfCqMv--ncA",
        title: "All The Stars ft. SZA (Black Panther)",
        channel: "Kendrick Lamar",
        duration: "3:55",
        thumbnail: "https://i.ytimg.com/vi/GfCqMv--ncA/hqdefault.jpg",
        views: "470M views",
        date: "Black Panther OST",
      },
      {
        id: "hRK7PVJFbS8",
        title: "King Kunta (Official Video)",
        channel: "Kendrick Lamar",
        duration: "3:58",
        thumbnail: "https://i.ytimg.com/vi/hRK7PVJFbS8/hqdefault.jpg",
        views: "210M views",
        date: "To Pimp a Butterfly",
      },
      {
        id: "uAXxkNaRkp8",
        title: "The Heart Part 5",
        channel: "Kendrick Lamar",
        duration: "5:32",
        thumbnail: "https://i.ytimg.com/vi/uAXxkNaRkp8/hqdefault.jpg",
        views: "58M views",
        date: "Mr. Morale",
      },
    ],
  },

  "Bruno Mars": {
    name: "Bruno Mars",
    handle: "@BrunoMars",
    cover:
      "https://yt3.googleusercontent.com/dxwzp4IYsNJKDcwNYgF0UGdw9vCWSMqkHaLtC08VVKg8eybNs69pbdTaGdoaKQYHVQjFyeybzA=s900-c-k-c0x00ffffff-no-rj",
    fallbackCover: oceanCover,
    banner:
      "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=1200&auto=format&fit=crop&q=80",
    subscribers: "38.5M subscribers",
    videosCount: "94 videos",
    totalViews: "22.8B views",
    bio: "Official YouTube Channel of Bruno Mars. Multi Grammy Award-winning artist, producer, and performer.",
    verified: true,
    featuredVideos: [
      {
        id: "kPa7bsKwL-8",
        title: "Die With A Smile (with Lady Gaga) [Official Video]",
        channel: "Lady Gaga & Bruno Mars",
        duration: "4:12",
        thumbnail: "https://i.ytimg.com/vi/kPa7bsKwL-8/hqdefault.jpg",
        views: "310M views",
        date: "2024 Global #1",
      },
      {
        id: "PMivT7MJ41M",
        title: "That's What I Like (Official Music Video)",
        channel: "Bruno Mars",
        duration: "3:26",
        thumbnail: "https://i.ytimg.com/vi/PMivT7MJ41M/hqdefault.jpg",
        views: "2.2B views",
        date: "24K Magic",
      },
      {
        id: "OPf0YbXqDm0",
        title: "Uptown Funk (feat. Bruno Mars)",
        channel: "Mark Ronson",
        duration: "4:30",
        thumbnail: "https://i.ytimg.com/vi/OPf0YbXqDm0/hqdefault.jpg",
        views: "5.3B views",
        date: "Classic Hit",
      },
      {
        id: "UqyT8IEBkvY",
        title: "24K Magic (Official Music Video)",
        channel: "Bruno Mars",
        duration: "3:46",
        thumbnail: "https://i.ytimg.com/vi/UqyT8IEBkvY/hqdefault.jpg",
        views: "1.6B views",
        date: "24K Magic",
      },
      {
        id: "adLGHcj_fmA",
        title: "Leave The Door Open (Silk Sonic)",
        channel: "Bruno Mars",
        duration: "4:02",
        thumbnail: "https://i.ytimg.com/vi/adLGHcj_fmA/hqdefault.jpg",
        views: "820M views",
        date: "Silk Sonic",
      },
      {
        id: "fLexgOxsZu0",
        title: "Locked Out Of Heaven (Official Music Video)",
        channel: "Bruno Mars",
        duration: "3:53",
        thumbnail: "https://i.ytimg.com/vi/fLexgOxsZu0/hqdefault.jpg",
        views: "1.1B views",
        date: "Unorthodox Jukebox",
      },
    ],
  },

  "Taylor Swift": {
    name: "Taylor Swift",
    handle: "@TaylorSwift",
    cover:
      "https://yt3.googleusercontent.com/o0vF7P3nF9C4p0VlSgH9P2u1KqX8r7F4f_g2T6=s900-c-k-c0x00ffffff-no-rj",
    fallbackCover: sunflowerCover,
    banner:
      "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=1200&auto=format&fit=crop&q=80",
    subscribers: "59.8M subscribers",
    videosCount: "260 videos",
    totalViews: "38.2B views",
    bio: "Official YouTube Channel of Taylor Swift. Stream THE TORTURED POETS DEPARTMENT and music from every era.",
    verified: true,
    featuredVideos: [
      {
        id: "q3zqJs7JUCQ",
        title: "Fortnight ft. Post Malone (Official Music Video)",
        channel: "Taylor Swift",
        duration: "4:09",
        thumbnail: "https://i.ytimg.com/vi/q3zqJs7JUCQ/hqdefault.jpg",
        views: "115M views",
        date: "TTPD",
      },
      {
        id: "b1kbLwvqugk",
        title: "Anti-Hero (Official Music Video)",
        channel: "Taylor Swift",
        duration: "5:09",
        thumbnail: "https://i.ytimg.com/vi/b1kbLwvqugk/hqdefault.jpg",
        views: "210M views",
        date: "Midnights",
      },
      {
        id: "3tmd-ClpJxA",
        title: "Look What You Made Me Do (Official Video)",
        channel: "Taylor Swift",
        duration: "4:15",
        thumbnail: "https://i.ytimg.com/vi/3tmd-ClpJxA/hqdefault.jpg",
        views: "1.5B views",
        date: "Reputation",
      },
      {
        id: "e-ORhEE9VVg",
        title: "Blank Space (Official Music Video)",
        channel: "Taylor Swift",
        duration: "4:32",
        thumbnail: "https://i.ytimg.com/vi/e-ORhEE9VVg/hqdefault.jpg",
        views: "3.4B views",
        date: "1989",
      },
      {
        id: "nfWlot6h_JM",
        title: "Shake It Off (Official Music Video)",
        channel: "Taylor Swift",
        duration: "4:01",
        thumbnail: "https://i.ytimg.com/vi/nfWlot6h_JM/hqdefault.jpg",
        views: "3.5B views",
        date: "1989",
      },
      {
        id: "VuNIsY6JdUw",
        title: "You Belong With Me",
        channel: "Taylor Swift",
        duration: "3:48",
        thumbnail: "https://i.ytimg.com/vi/VuNIsY6JdUw/hqdefault.jpg",
        views: "1.6B views",
        date: "Fearless",
      },
    ],
  },

  "Sabrina Carpenter": {
    name: "Sabrina Carpenter",
    handle: "@SabrinaCarpenter",
    cover: "https://yt3.googleusercontent.com/fL3sT7jV0pW5r3q2K8=s900-c-k-c0x00ffffff-no-rj",
    fallbackCover: oceanCover,
    banner:
      "https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=1200&auto=format&fit=crop&q=80",
    subscribers: "11.8M subscribers",
    videosCount: "110 videos",
    totalViews: "6.4B views",
    bio: "Official YouTube Channel of Sabrina Carpenter. Stream new album 'Short n' Sweet' out now.",
    verified: true,
    featuredVideos: [
      {
        id: "kPqg7K7U1Lw",
        title: "Espresso (Official Music Video)",
        channel: "Sabrina Carpenter",
        duration: "3:20",
        thumbnail: "https://i.ytimg.com/vi/kPqg7K7U1Lw/hqdefault.jpg",
        views: "240M views",
        date: "Short n' Sweet",
      },
      {
        id: "cF1Na4AIecM",
        title: "Please Please Please (Official Music Video)",
        channel: "Sabrina Carpenter",
        duration: "4:10",
        thumbnail: "https://i.ytimg.com/vi/cF1Na4AIecM/hqdefault.jpg",
        views: "160M views",
        date: "Short n' Sweet",
      },
      {
        id: "k6SwXvWJ5c0",
        title: "Taste (Official Music Video)",
        channel: "Sabrina Carpenter",
        duration: "3:10",
        thumbnail: "https://i.ytimg.com/vi/k6SwXvWJ5c0/hqdefault.jpg",
        views: "120M views",
        date: "Short n' Sweet",
      },
      {
        id: "O_tT2Zf9D80",
        title: "Feather (Official Music Video)",
        channel: "Sabrina Carpenter",
        duration: "3:15",
        thumbnail: "https://i.ytimg.com/vi/O_tT2Zf9D80/hqdefault.jpg",
        views: "110M views",
        date: "emails i can't send",
      },
    ],
  },

  "Daft Punk": {
    name: "Daft Punk",
    handle: "@DaftPunk",
    cover:
      "https://yt3.googleusercontent.com/XPIjND5mm2nuSIJ6uQyIWLCawnIYSVm6QS0GEN_UNuPLRD5EFa6yCkYrcyLpl3TFuBo6AZynsA=s900-c-k-c0x00ffffff-no-rj",
    fallbackCover: dawnCover,
    banner:
      "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1200&auto=format&fit=crop&q=80",
    subscribers: "6.52M subscribers",
    videosCount: "74 videos",
    totalViews: "6.8B views",
    bio: "Official YouTube Channel of Daft Punk. Guy-Manuel de Homem-Christo and Thomas Bangalter (1993-2021).",
    verified: true,
    featuredVideos: [
      {
        id: "5NV6Rdv1a3I",
        title: "Get Lucky ft. Pharrell Williams (Official Video)",
        channel: "Daft Punk",
        duration: "4:08",
        thumbnail: "https://i.ytimg.com/vi/5NV6Rdv1a3I/hqdefault.jpg",
        views: "910M views",
        date: "Random Access Memories",
      },
      {
        id: "k5w2MvtVb6Q",
        title: "Around the World (Official Music Video)",
        channel: "Daft Punk",
        duration: "4:00",
        thumbnail: "https://i.ytimg.com/vi/k5w2MvtVb6Q/hqdefault.jpg",
        views: "180M views",
        date: "Homework",
      },
      {
        id: "FGBhQbmMxH8",
        title: "One More Time (Official Video)",
        channel: "Daft Punk",
        duration: "5:20",
        thumbnail: "https://i.ytimg.com/vi/FGBhQbmMxH8/hqdefault.jpg",
        views: "520M views",
        date: "Discovery",
      },
      {
        id: "gAjR4_CbPpQ",
        title: "Harder, Better, Faster, Stronger (Official Video)",
        channel: "Daft Punk",
        duration: "3:44",
        thumbnail: "https://i.ytimg.com/vi/gAjR4_CbPpQ/hqdefault.jpg",
        views: "230M views",
        date: "Discovery",
      },
      {
        id: "a5uQMwRMHcs",
        title: "Instant Crush ft. Julian Casablancas",
        channel: "Daft Punk",
        duration: "5:39",
        thumbnail: "https://i.ytimg.com/vi/a5uQMwRMHcs/hqdefault.jpg",
        views: "640M views",
        date: "Random Access Memories",
      },
    ],
  },

  "Frank Ocean": {
    name: "Frank Ocean",
    handle: "@FrankOcean",
    cover:
      "https://yt3.googleusercontent.com/ytc/AIdro_nLfOnFMQ6NzSrw2H6I0IxTOTRaFU4KZF3Ivl1BybLM4uIzdNMIJ_YKaZy2rosNSpTifw=s900-c-k-c0x00ffffff-no-rj",
    fallbackCover: tranquilityCover,
    banner:
      "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=1200&auto=format&fit=crop&q=80",
    subscribers: "4.85M subscribers",
    videosCount: "42 videos",
    totalViews: "4.2B views",
    bio: "Official Channel of Frank Ocean. channel ORANGE, Blonde, and singles.",
    verified: true,
    featuredVideos: [
      {
        id: "BAzP6oE8d_I",
        title: "Lost (Official Video)",
        channel: "Frank Ocean",
        duration: "3:54",
        thumbnail: "https://i.ytimg.com/vi/BAzP6oE8d_I/hqdefault.jpg",
        views: "210M views",
        date: "channel ORANGE",
      },
      {
        id: "TMfPJT4XjGQ",
        title: "Novacane (Official Video)",
        channel: "Frank Ocean",
        duration: "3:50",
        thumbnail: "https://i.ytimg.com/vi/TMfPJT4XjGQ/hqdefault.jpg",
        views: "98M views",
        date: "nostalgia, ULTRA",
      },
      {
        id: "F15IjgyHd44",
        title: "Thinkin Bout You",
        channel: "Frank Ocean",
        duration: "3:20",
        thumbnail: "https://i.ytimg.com/vi/F15IjgyHd44/hqdefault.jpg",
        views: "280M views",
        date: "channel ORANGE",
      },
      {
        id: "s26qTrH2atA",
        title: "Pyramids (Explicit)",
        channel: "Frank Ocean",
        duration: "9:52",
        thumbnail: "https://i.ytimg.com/vi/s26qTrH2atA/hqdefault.jpg",
        views: "78M views",
        date: "channel ORANGE",
      },
      {
        id: "MRy_Yq6g57M",
        title: "Chanel",
        channel: "Frank Ocean",
        duration: "3:30",
        thumbnail: "https://i.ytimg.com/vi/MRy_Yq6g57M/hqdefault.jpg",
        views: "110M views",
        date: "Blonded Single",
      },
    ],
  },
};

export const POPULAR_MUSIC_HITS: ArtistVideo[] = [
  {
    id: "V9PVRfjEBTI",
    title: "BIRDS OF A FEATHER",
    channel: "Billie Eilish",
    duration: "3:13",
    thumbnail: "https://i.ytimg.com/vi/V9PVRfjEBTI/hqdefault.jpg",
    views: "120M views",
    date: "HIT ME HARD AND SOFT",
  },
  {
    id: "kPa7bsKwL-8",
    title: "Die With A Smile",
    channel: "Lady Gaga & Bruno Mars",
    duration: "4:12",
    thumbnail: "https://i.ytimg.com/vi/kPa7bsKwL-8/hqdefault.jpg",
    views: "310M views",
    date: "Top Hit Worldwide",
  },
  {
    id: "H58vbez_m4E",
    title: "Not Like Us",
    channel: "Kendrick Lamar",
    duration: "4:34",
    thumbnail: "https://i.ytimg.com/vi/H58vbez_m4E/hqdefault.jpg",
    views: "180M views",
    date: "Chart Topper",
  },
  {
    id: "m7FkZ_9pL1A",
    title: "Dancing in the Flames",
    channel: "The Weeknd",
    duration: "3:40",
    thumbnail: "https://i.ytimg.com/vi/m7FkZ_9pL1A/hqdefault.jpg",
    views: "45M views",
    date: "Latest Release",
  },
  {
    id: "MB3VkzPdgLA",
    title: "LUNCH",
    channel: "Billie Eilish",
    duration: "3:00",
    thumbnail: "https://i.ytimg.com/vi/MB3VkzPdgLA/hqdefault.jpg",
    views: "85M views",
    date: "HIT ME HARD AND SOFT",
  },
  {
    id: "kPqg7K7U1Lw",
    title: "Espresso",
    channel: "Sabrina Carpenter",
    duration: "3:20",
    thumbnail: "https://i.ytimg.com/vi/kPqg7K7U1Lw/hqdefault.jpg",
    views: "240M views",
    date: "Summer Anthem",
  },
  {
    id: "q3zqJs7JUCQ",
    title: "Fortnight ft. Post Malone",
    channel: "Taylor Swift",
    duration: "4:09",
    thumbnail: "https://i.ytimg.com/vi/q3zqJs7JUCQ/hqdefault.jpg",
    views: "115M views",
    date: "TTPD",
  },
  {
    id: "4NRXx6U8ABQ",
    title: "Blinding Lights",
    channel: "The Weeknd",
    duration: "4:20",
    thumbnail: "https://i.ytimg.com/vi/4NRXx6U8ABQ/hqdefault.jpg",
    views: "890M views",
    date: "Global Classic",
  },
  {
    id: "PMivT7MJ41M",
    title: "That's What I Like",
    channel: "Bruno Mars",
    duration: "3:26",
    thumbnail: "https://i.ytimg.com/vi/PMivT7MJ41M/hqdefault.jpg",
    views: "2.2B views",
    date: "24K Magic",
  },
  {
    id: "DyDfgMOUjCI",
    title: "bad guy",
    channel: "Billie Eilish",
    duration: "3:25",
    thumbnail: "https://i.ytimg.com/vi/DyDfgMOUjCI/hqdefault.jpg",
    views: "1.3B views",
    date: "Grammy Record of the Year",
  },
];

export const POPULAR_ARTIST_NAMES = [
  "Billie Eilish",
  "The Weeknd",
  "Kendrick Lamar",
  "Bruno Mars",
  "Taylor Swift",
  "Sabrina Carpenter",
  "Daft Punk",
  "Frank Ocean",
];
